language: python

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.6"
      env: TOXENV=py36
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
    - python: "3.9"
      env: TOXENV=py39

addons:
  postgresql: "9.3"

services:
  - postgresql

before_install:
  - pip install --upgrade pip
  - pip install tox

before_script:
  - psql -c 'create database images;' -U postgres

script:
  - tox

after_success:
  - pip install coveralls
  - coveralls
