# Generated by Django 4.2.6 on 2023-10-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processer', '0002_uploadedimage_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='social_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='social_provider',
            field=models.CharField(blank=True, choices=[('1', 'Facebook')], max_length=1, null=True),
        ),
    ]
