# Generated by Django 4.2.6 on 2023-10-09 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processer', '0003_uploadedimage_social_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='social_provider',
        ),
    ]
