# Generated by Django 4.2.6 on 2023-10-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processer', '0004_remove_uploadedimage_social_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='effects',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='social_id',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='exposure',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='filter_type',
            field=models.CharField(blank=True, choices=[('vivid', 'Vivid'), ('vivid_warm', 'Vivid Warm'), ('dramatic', 'Dramatic')], max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='highlight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='shadows',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='shared_on_social_media',
            field=models.BooleanField(default=False),
        ),
    ]
