# Generated by Django 4.2.6 on 2023-10-10 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processer', '0006_uploadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.AlterModelOptions(
            name='uploadedimage',
            options={'ordering': ('-modified_on',)},
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='exposure',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='filter_type',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='highlight',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='shadows',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='shared_on_social_media',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='title',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='edited',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='profile/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
